### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by StevenProhashing** [pmmp/pthreads#75]
PHP 8.1 currently isn't supported, right? Will PHP 8.1 be supported?

Thanks.

**Comment by dktapps** [comment]
Eventually, but I don't have the time or plans to do it in the near future

**Comment by dktapps** [comment]
As of this commit, the primary branch now supports 8.1: ec0c1834134f43f04ba5a8989a533505d5079079

However, you should expect that some things are not gonna work, such as object constants.
I haven't battle-tested it yet, so it's likely there will be broken things (that's usually the way this goes, due to how complex pthreads is).
