### ISSUE TITLE
Where I can find the binaries link for windows version?

### ISSUE THREAD

**Issue by hAbd0u** [pmmp/pthreads#76]
Hello,
First, thank you for your efforts to continue maintaining it and add support to PHP 7.*. 
As you said in the main repo page, windows is supported but unfortunately I couldn't find the download links, would you provide it for PHP 7.4?

**Comment by dktapps** [comment]
Hi, we don't currently maintain any release binaries since this fork is primarily intended for PocketMine-MP usage, and we ship our own custom PHP binaries for PocketMine-MP which include pthreads. You're welcome to check out the artifacts in [php-build-scripts actions](https://github.com/pmmp/php-build-scripts/actions) (you'll need to take bin/php/pthreadvc3.dll and bin/php/ext/php_pthreads.dll).

**Comment by hAbd0u** [comment]
@dktapps Ok, I will try later to compile it.
